### ISSUE TITLE
sendchildorderでエラーがでてしまいます…

### ISSUE THREAD

**Issue by sho-yamane** [yagays/pybitflyer#9]
便利なライブラリーのご提供ありがとうございます。

ごくたまになのですが注文sendchildorderをすると以下のようなエラーを吐いてしまいます。

もしよろしければご確認よろしくお願いいたします。

```
Traceback (most recent call last):
  File "index.py", line 144, in <module>
    bfbot.main()
  File "index.py", line 132, in main
    self.buyBtc()
  File "index.py", line 77, in buyBtc
    time_in_force = "GTC"
  File "/Users/XXXXXX/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pybitflyer/pybitflyer.py", line 481, in sendchildorder
    return self.request(endpoint, "POST", params=params)
  File "/Users/XXXXXX/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pybitflyer/pybitflyer.py", line 60, in request
    content = json.loads(response.content.decode("utf-8"))
  File "/Users/XXXXXX/.pyenv/versions/3.6.0/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/XXXXXX/.pyenv/versions/3.6.0/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/XXXXXX/.pyenv/versions/3.6.0/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by lhsfcboy** [comment]
bitFlyer did not guarantee that your request will be accepted, even everything is fine. 
In your case, I **guess** its because bitFlyer didnt respond anything to your new order.

It is not a problem of this lib, although it would be nicer to catch these exception inside this lib.
However, it will be a problem of design, 
that how much should you expect from this lib. 

I think this lib should be used as a pure wrapper of native API, 
you should handle above exception in your code.
But again, it will be nicer if we have that *response.content* in return.

You must check any operation that is out of your control.
You send order and bitFlyer accept it, in this process, you dont know how bitFlyer will respond, 
you can only EXPECT their response. 
Hence, you must check it.

**Comment by lhsfcboy** [comment]
By they way, I think I acught the output of this error,

response.content will be likw below

b'<!DOCTYPE html>\n\n\n\n <html class="no-js" lang="en-US"> \n<head>\n<title>api.bitflyer.jp | 524: A timeout occurred</title>\n<meta charset="UTF-8" />\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />\n<meta name="robots" content="noindex, nofollow" />\n<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />\n<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />\n\n<style type="text/css">body{margin:0;padding:0}</style>\n\n<script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script>\n<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>\n</head>\n<body>\n<div id="cf-wrapper">\n<div id="cf-error-details" class="cf-error-details-wrapper">\n<div class="cf-wrapper cf-error-overview">\n<h1>\n<span class="cf-error-type" data-translate="error">Error</span>\n<span class="cf-error-code">524</span>\n<small class="heading-ray-id">Ray ID: 3ebd6c5369c094ed &bull; 2018-02-12 06:18:48 UTC</small>\n</h1>\n<h2 class="cf-subheadline" data-translate="error_desc">A timeout occurred</h2>\n</div>\n<div class="cf-section cf-highlight cf-status-display">\n<div class="cf-wrapper">\n<div class="cf-columns cols-3">\n<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">\n<div class="cf-icon-error-container">\n<i class="cf-icon cf-icon-browser"></i>\n<i class="cf-icon-status cf-icon-ok"></i>\n</div>\n<span class="cf-status-desc" data-translate="browser_desc">You</span>\n<h3 class="cf-status-name" data-translate="browser_label">Browser</h3>\n<span class="cf-status-label" data-translate="browser_status_label">Working</span>\n</div>\n<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">\n<div class="cf-icon-error-container">\n<i class="cf-icon cf-icon-cloud"></i>\n<i class="cf-icon-status cf-icon-ok"></i>\n</div>\n<span class="cf-status-desc" data-translate="cloud_desc">Tokyo</span>\n<h3 class="cf-status-name" data-translate="cloud_label">Cloudflare</h3>\n<span class="cf-status-label" data-translate="cloud_status_label">Working</span>\n</div>\n<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">\n<div class="cf-icon-error-container">\n<i class="cf-icon cf-icon-server"></i>\n<i class="cf-icon-status cf-icon-error"></i>\n</div>\n<span class="cf-status-desc" data-translate="server_desc">api.bitflyer.jp</span>\n<h3 class="cf-status-name" data-translate="server_label">Host</h3>\n<span class="cf-status-label" data-translate="server_status_label">Error</span>\n</div>\n</div>\n</div>\n</div>\n<div class="cf-section cf-wrapper">\n<div class="cf-columns two">\n<div class="cf-column">\n<h2 data-translate="what_happened">What happened?</h2>\n<p data-translate="origin_timed_out">The origin web server timed out responding to this request.</p>\n</div>\n<div class="cf-column">\n<h2 data-translate="what_can_i_do">What can I do?</h2>\n<h5 data-translate="if_website_visitor">If you\'re a visitor of this website:</h5>\n<p data-translate="try_again_in_a_few">Please try again in a few minutes.</p>\n<h5 data-translate="if_website_owner">If you\'re the owner of this website:</h5>\n<p><span data-translate="524_owner_desc">The connection to the origin web server was made, but the origin web server timed out before responding. The likely cause is an overloaded background task, database or application, stressing the resources on your web server. To resolve, please work with your hosting provider or web development team to free up resources for your database or overloaded application.</span> <a href="https://support.cloudflare.com/hc/en-us/articles/200171926-Error-524" data-translate="addtl_troubleshooting">Additional troubleshooting information here.</a></p>\n</div>\n</div>\n</div>\n<div class="cf-error-footer cf-wrapper">\n<p>\n<span class="cf-footer-item">Cloudflare Ray ID: <strong>3ebd6c5369c094ed</strong></span>\n<span class="cf-footer-separator">&bull;</span>\n<span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: 240f:79:3f86:1:6cc8:c9d6:ccb1:2306</span>\n<span class="cf-footer-separator">&bull;</span>\n<span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>\n</p>\n</div>\n</div>\n</div>\n'

**Comment by nagadomi** [comment]
That is an error response from Cloudflare(CDN of API server). When bitflyer's API server is down, API returns that response.
If you want to detect the timeout error more quickly, specify the `timeout` option.
```
api = pybitflyer.API(timeout=30)
```
`requests.exceptions.ConnectTimeout` or `requests.exceptions.ReadTimeout` will be raise if there is no response from API server for 30 seconds.

**Comment by toshiosawa** [comment]
error :+1: 
File "pybitflyer.py", line 9, in <module>
    from .exception import AuthException
ModuleNotFoundError: No module named '__main__.exception'; '__main__' is not a package

Please tell us what to do

**Comment by toshiosawa** [comment]
error 
File "pybitflyer.py", line 9, in
from .exception import AuthException
ModuleNotFoundError: No module named 'main.exception'; 'main' is not a package

Please tell us what to do

**Comment by tommygoo** [comment]
error !!
File "pybitflyer.py", line 9, in
from .exception import AuthException
ModuleNotFoundError: No module named 'main.exception'; 'main' is not a package

Please tell us what to do

**Comment by tommygoo** [comment]
error !!
File "pybitflyer.py", line 9, in
from .exception import AuthException
ModuleNotFoundError: No module named 'main.exception'; 'main' is not a package

Please tell me what to do
